# Generated by Django 3.1 on 2020-09-01 17:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mywebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_news',
            name='news_detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
