# Generated by Django 3.1 on 2020-09-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mywebsite', '0002_auto_20200902_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_news',
            name='news_detail',
            field=models.TextField(default=''),
        ),
    ]
